config/routes.rb
Rails.application.routes.draw do
  mount Documentation::Engine => "/docs"
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'sessions' }
  ActiveAdmin.routes(self)
  root 'admin/dashboard#index'

  resources :users, only: [:create, :show, :update]
  resources :contact_emails, only: [:create]
  resources :restaurants, only: [:index, :show]
  resources :services, only: [:index, :update]
  resources :reservations, only: [:index,:create, :update]
  resources :transactions, only: [:index]

  get 'resend_confirmation', to: 'users#resend_confirmation', 
                             as: 'resend_confirmation'
  get 'confirm', to: 'users#confirm', as: 'confirm'
  get 'password_email', to: 'users#password_email', as: 'password_email'
  get 'edit_password', to: 'users#edit_password', as: 'edit_password'
  post 'update_password', to: 'users#update_password', as: 'update_password'
  get 'unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
end

app/models/service.rb
class Service < ActiveRecord::Base

  include Archiving

  enum status: [ :complete, :available ]

  has_many :reservations
  belongs_to :restaurant
  belongs_to :service_template

  just_define_datetime_picker :start_time
  just_define_datetime_picker :last_booking_time

  after_create :update_current_discount

  
  def self.future_with_availabilities
    self.today_or_future.where(
      "current_discount > :zero",
      { zero: 0 }
    )
  end

  def self.today_or_future
    self.where(
      "start_time > :yesterday",
      { yesterday: Time.new.midnight }
    )
  end

  def self.get_template_services_for_day(service_template_id, day)
    where(service_template_id: service_template_id)
    .where(template_day: day)
    .get_unarchived
  end

  #get services that match date
  #used for services calendar
  def self.get_services_for_day date
    date_day = date.day
    date_month = date.month
    date_year = date.year
    service_ids = []
    find_each do |s|
      service_time = s.start_time
      if service_time &&
        service_time.day === date_day &&
        service_time.month === date_month &&
        service_time.year === date_year 
        service_ids << s.id
      end
    end
    where(id: service_ids)
  end

  #don't get services where restaurants said they 
  #were complete (full)
  def self.not_complete
    self.where(id: get_not_complete_ids).get_unarchived
  end

  def self.get_not_complete_ids
    s_ids = []
    self.all.each do |s|
      if s.status != Service.statuses[:complete]      
          s_ids << s.id    
          end  
      end    
  end

  def self.check_and_update(owner_id, params)
    service_id = params[:id].to_i
    restaurant_id = params[:service][:restaurant_id].to_i
    service = Service.find(service_id)
    user = User.find(owner_id)

    #Authorization: start checking credentials and associations
    if user.is_owner? &&
      service &&
      user.restaurants.first.service_ids.include?(service_id) &&
      user.restaurant_ids.include?(restaurant_id) &&
      service.restaurant_id === restaurant_id 

      #update and save
      if service.status == nil || service.status == "available"
        service.complete!
      else
        service.available!
      end

      service.save!
      return true
    else
      return false
    end
  end

  #get services between specific times
  def self.services_within_time_period(other_start_time, 
                                       other_end_time)
    self.where(
      "start_time <= :other_start_time AND last_booking_time >= :other_start_time OR 
       start_time <= :other_end_time AND last_booking_time >= :other_end_time",
      { 
        other_start_time: other_start_time,
        other_end_time: other_end_time
      }
    )
  end

  def self.get_service params

  	#add service 
    #get restaurant
    restaurant = Restaurant.find(params[:reservation][:restaurant_id].to_i)
    
    #get service based on times
    service = restaurant.services.get_unarchived.where(
      "start_time <= :time AND last_booking_time >= :time",
      { time: params[:reservation][:time] }
    ).first

    #update service params
    return service
  end

  def update_current_discount
    service = self
    #get spots already taken
    availabilities = service.availabilities
    spots_taken = service.reservations.get_unarchived.not_cancelled.count

    #get percentage availabilites
    number_of_ten_available = service.nb_10
    number_of_fifteen_available = service.nb_15
    number_of_twenty_available = service.nb_20
    number_of_twenty_five_available = service.nb_25

    #get new current discount
    #return 0 if no spots left
    if spots_taken >= availabilities 
      discount = 0
    #start highest to lowest percentages 
    #to see which percentage is still available 
    elsif spots_taken < number_of_twenty_five_available
      discount = 0.25
    elsif spots_taken < number_of_twenty_available
      discount = 0.20
    elsif spots_taken < number_of_fifteen_available
      discount = 0.15
    else
      discount = 0.10
    end
    
    service.update(current_discount: discount)
  end

  def service_params
    params.require(:service).permit(:availabilities, :start_time, :last_booking_time,
                :restaurant_id, :nb_10, :nb_15, :nb_20, :nb_25,
                :start_time_date, :start_time_time_hour, :start_time_time_minute,
                :last_booking_time_date, :last_booking_time_time_hour, 
                :last_booking_time_time_minute, :service_template_id, :service_template,
                :template_day)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	
	#GET /services?restaurant_id=:id
	def index
		if user_signed_in?
			if (restaurant = Restaurant.find(params[:restaurant_id]))
				#if this is for an owner, don't get more than needed
				if restaurant.user == current_user
					services = restaurant.services.get_unarchived.future_with_availabilities.first(30)
				else
					services = restaurant.services.get_unarchived.future_with_availabilities
				end
				render json: services
			else
				services = Service.get_unarchived.future_with_availabilities
				render json: services
			end
		else
			head 401
		end
	end

	def update
    if user_signed_in?
      #check to make sure user is owner and service belongs to
      #owner then update if it is
      if Service.check_and_update(current_user.id, params)
        head 204
      else
        head 422
      end
    else
      head 401
    end
  end
end

app/views/admin/services/_restaurant_templates_select.haml
- templates = ServiceTemplate.get_unarchived.where(restaurant_id: nil)
- ServiceTemplate.get_unarchived.where(restaurant_id: restaurant.id).each { |t| templates << t }
- template_array = templates.map { |t| [ServiceTemplate.find(t.id).restaurant_id ? t.name : t.name + " (Master)", t.id] }
#template-box
	%h5 Update services using template?
	= form_tag admin_restaurant_services_url do
		= hidden_field_tag :batch_action, :use_templates_for_services
		= hidden_field_tag :batch_action_inputs, {}
		= hidden_field_tag :restaurant_id, restaurant.id
		= hidden_field_tag :date, date
		= label_tag :service_template_id, "Template  "
		= select_tag :service_template_id, options_for_select(template_array)
		%span Please choose weeks for Calendar below to apply template to:
		%span
			= check_box_tag(:week_one)
			= label_tag(:week_one, "Week One") 
		%span
			= check_box_tag(:week_two)
			= label_tag(:week_two, "Week Two") 
		%span
			= check_box_tag(:week_three)
			= label_tag(:week_three, "Week Three") 
		%span
			= check_box_tag(:week_four)
			= label_tag(:week_four, "Week Four") 
		%span
			= check_box_tag(:week_five)
			= label_tag(:week_five, "Week Five")
		%span
			= check_box_tag(:week_six)
			= label_tag(:week_six, "Week Six")
		%span
			= check_box_tag(:whole_month)
			= label_tag(:whole_month, "Whole Month")
		%span
			= check_box_tag(:whole_year)
			= label_tag(:whole_year, "Next Three Months")
		%span
			%br
			%br
			= submit_tag "Apply Template"

app/views/admin/services/_service_calendar.haml
%link(href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet")
- @date = session[:date] != nil ? session[:date].to_date : params[:date] ? Date.parse(params[:date]) : Date.today
- session[:date] = nil if session[:date]
-if @date.nil?
	- @date = Date.today
= render partial: "restaurant_templates_select", locals: { restaurant: Restaurant.find(params[:restaurant_id]), date: @date }
- services = restaurant.services.get_unarchived
#service-calendar
	%h2#month
		= link_to "<", date: @date.prev_month 
		= @date.strftime("%B %Y") 
		= link_to ">", date: @date.next_month
	%br
	= calendar @date do |date| 
		#calendar-date 
			= date.day 
			- day_services = services.get_services_for_day date
		= link_to new_admin_restaurant_service_path(restaurant) do
			%i.fa.fa-plus-circle#plus-button
		- day_services.each do |service|
			=link_to admin_restaurant_service_path(restaurant, service) do 
				.calendar-service-times
					= service.start_time.strftime('%H:%M') + ' to' 
					= service.last_booking_time.strftime('%H:%M')
					- message = "Are you sure you want to delete this service for " + Restaurant.find(params[:restaurant_id]).name + "? This cannot be undone!"
					=link_to admin_restaurant_service_url(params[:restaurant_id], service), method: :delete, data: { confirm: message } do 
						%i.fa.fa-minus-circle#minus-circle
#template-box
	%h5 
		Want to delete all services?

	#service-delete-link
		- message = "Are you sure you want to delete all services for " + Restaurant.find(params[:restaurant_id]).name + "? This cannot be undone!"
		=link_to admin_restaurant_service_url(params[:restaurant_id], 1, delete_all_services: true), method: :delete, data: { confirm: message } do 
			%span#delete-services-button 
				DELETE ALL SERVICES
				%i.fa.fa-warning
		